### ISSUE TITLE
Milestone2: 2nd meeting minutes

### ISSUE THREAD

**Issue by wang-rui** [UBC-MDS/522_group-33#24]
**Meeting minutes- 2020-11-27**

**Tasks Finished:**

Went through everyone's tasks and merged PR requests.

**Pending tasks for the next meeting (2020-11-28 4PM GMT +8**)
Bruhat: 

- [ ] Apply SMOTE to deal with class imbalance. 

- [ ] Modify the .ipynb to .py script files. 

Sang Yoon: 

- [ ] Edit Preprocessing script and incorporate data splitting parts. 

Rui: 

- [ ] Update Dependency YAML files

- [ ] Find the reference articles

Alex: 

- [ ] Finish the full report with EDA and model links.
